//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 02:08:09 PM PET 
//


package services.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Header complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Header"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="requestId" type="{http://ibk.com/ents/SOI/CoreExtensions/V5.0}RequestId"/&gt;
 *         &lt;element name="identidad" type="{http://ibk.com/ents/SOI/CoreExtensions/V5.0}Identidad"/&gt;
 *         &lt;element name="messageContext" type="{http://ibk.com/ents/SOI/CoreExtensions/V5.0}MessageContext" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Header", namespace = "http://ibk.com/ents/SOI/MessageFormat/V5.0", propOrder = {
    "requestId",
    "identidad",
    "messageContext"
})
@XmlSeeAlso({
    RequestHeader.class,
    ResponseHeader.class
})
public abstract class Header {

    @XmlElement(required = true)
    protected RequestId requestId;
    @XmlElement(required = true)
    protected Identidad identidad;
    protected MessageContext messageContext;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link RequestId }
     *     
     */
    public RequestId getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestId }
     *     
     */
    public void setRequestId(RequestId value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the identidad property.
     * 
     * @return
     *     possible object is
     *     {@link Identidad }
     *     
     */
    public Identidad getIdentidad() {
        return identidad;
    }

    /**
     * Sets the value of the identidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identidad }
     *     
     */
    public void setIdentidad(Identidad value) {
        this.identidad = value;
    }

    /**
     * Gets the value of the messageContext property.
     * 
     * @return
     *     possible object is
     *     {@link MessageContext }
     *     
     */
    public MessageContext getMessageContext() {
        return messageContext;
    }

    /**
     * Sets the value of the messageContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageContext }
     *     
     */
    public void setMessageContext(MessageContext value) {
        this.messageContext = value;
    }

}
