//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 02:08:09 PM PET 
//


package services.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestHeader"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ibk.com/ents/SOI/MessageFormat/V5.0}Header"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="userId" type="{http://ibk.com/ents/SOI/CoreExtensions/V5.0}UsernameToken" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="destination" type="{http://ibk.com/ents/SOI/CoreExtensions/V5.0}Destination" minOccurs="0"/&gt;
 *         &lt;element name="classifications" type="{http://ibk.com/ents/SOI/CoreExtensions/V5.0}Classifications" maxOccurs="0" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestHeader", namespace = "http://ibk.com/ents/SOI/MessageFormat/V5.0", propOrder = {
    "userId",
    "destination"
})
public class RequestHeader
    extends Header
{

    protected List<UsernameToken> userId;
    protected Destination destination;

    /**
     * Gets the value of the userId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UsernameToken }
     * 
     * 
     */
    public List<UsernameToken> getUserId() {
        if (userId == null) {
            userId = new ArrayList<UsernameToken>();
        }
        return this.userId;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link Destination }
     *     
     */
    public Destination getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Destination }
     *     
     */
    public void setDestination(Destination value) {
        this.destination = value;
    }

}
