//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 12:26:00 PM PET 
//


package services.campanias;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for ConsultarLeadResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsultarLeadResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cliente" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="idCliente" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="numeroDocumento" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="nombres" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="apellidos" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="email" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="leads" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lead" type="{http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0}Lead" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultarLeadResponse", propOrder = {
    "cliente",
    "leads"
})
public class ConsultarLeadResponse {

    protected ConsultarLeadResponse.Cliente cliente;
    protected ConsultarLeadResponse.Leads leads;

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultarLeadResponse.Cliente }
     *     
     */
    public ConsultarLeadResponse.Cliente getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultarLeadResponse.Cliente }
     *     
     */
    public void setCliente(ConsultarLeadResponse.Cliente value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the leads property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultarLeadResponse.Leads }
     *     
     */
    public ConsultarLeadResponse.Leads getLeads() {
        return leads;
    }

    /**
     * Sets the value of the leads property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultarLeadResponse.Leads }
     *     
     */
    public void setLeads(ConsultarLeadResponse.Leads value) {
        this.leads = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="idCliente" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="numeroDocumento" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="nombres" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="apellidos" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="email" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Cliente {

        @XmlAttribute(name = "idCliente")
        protected String idCliente;
        @XmlAttribute(name = "tipoDocumento")
        protected String tipoDocumento;
        @XmlAttribute(name = "numeroDocumento")
        protected String numeroDocumento;
        @XmlAttribute(name = "nombres")
        protected String nombres;
        @XmlAttribute(name = "apellidos")
        protected String apellidos;
        @XmlAttribute(name = "email")
        protected String email;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the idCliente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdCliente() {
            return idCliente;
        }

        /**
         * Sets the value of the idCliente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdCliente(String value) {
            this.idCliente = value;
        }

        /**
         * Gets the value of the tipoDocumento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoDocumento() {
            return tipoDocumento;
        }

        /**
         * Sets the value of the tipoDocumento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoDocumento(String value) {
            this.tipoDocumento = value;
        }

        /**
         * Gets the value of the numeroDocumento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeroDocumento() {
            return numeroDocumento;
        }

        /**
         * Sets the value of the numeroDocumento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeroDocumento(String value) {
            this.numeroDocumento = value;
        }

        /**
         * Gets the value of the nombres property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombres() {
            return nombres;
        }

        /**
         * Sets the value of the nombres property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombres(String value) {
            this.nombres = value;
        }

        /**
         * Gets the value of the apellidos property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApellidos() {
            return apellidos;
        }

        /**
         * Sets the value of the apellidos property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApellidos(String value) {
            this.apellidos = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lead" type="{http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0}Lead" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lead"
    })
    public static class Leads {

        protected List<Lead> lead;

        /**
         * Gets the value of the lead property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lead property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLead().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Lead }
         * 
         * 
         */
        public List<Lead> getLead() {
            if (lead == null) {
                lead = new ArrayList<Lead>();
            }
            return this.lead;
        }

    }

}
