//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 12:26:00 PM PET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0")
package services.campanias;
