<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="LeadCampanias"
	targetNamespace="http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/Enlace/V1.0"
	xmlns:tns="http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/Enlace/V1.0"
	xmlns:ns="http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<wsdl:import location="LeadCampanias_Intf_v1.wsdl"
		namespace="http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0"/>

	<wsdl:binding name="LeadCampanias_HttpBinding" type="ns:LeadCampanias">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="consultarLead">
			<soap:operation soapAction="http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0/consultarCampanias" />
			<wsdl:input name="consultarLeadRequest">
				<soap:body parts="parameters" use="literal" />
				<soap:header message="ns:consultarLeadRequestMsg" part="requestHeader" use="literal" />
			</wsdl:input>
			<wsdl:output name="consultarLeadResponse">
				<soap:body parts="result" use="literal" />
				<soap:header message="ns:consultarLeadResponseMsg" part="responseHeader" use="literal" />
			</wsdl:output>
			<wsdl:fault name="consultarLeadException">
				<soap:fault use="literal" name="consultarLeadException" />
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="actualizarLead">
			<soap:operation soapAction="http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0/actualizarLead" />
			<wsdl:input name="actualizarLeadRequest">
				<soap:body parts="parameters" use="literal" />
				<soap:header message="ns:actualizarLeadRequestMsg" part="requestHeader" use="literal" />
			</wsdl:input>
			<wsdl:output name="actualizarLeadResponse">
				<soap:body parts="result" use="literal" />
				<soap:header message="ns:actualizarLeadResponseMsg" part="responseHeader" use="literal" />
			</wsdl:output>
			<wsdl:fault name="actualizarLeadException">
				<soap:fault use="literal" name="actualizarLeadException" />
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="actualizarContador">
			<soap:operation soapAction="http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0/actualizarContador" />
			<wsdl:input name="actualizarContadorRequest">
				<soap:body parts="parameters" use="literal" />
				<soap:header message="ns:actualizarContadorRequestMsg" part="requestHeader" use="literal" />
			</wsdl:input>
			<wsdl:output name="actualizarContadorResponse">
				<soap:body parts="result" use="literal" />
				<soap:header message="ns:actualizarContadorResponseMsg" part="responseHeader" use="literal" />
			</wsdl:output>
			<wsdl:fault name="actualizarContadorException">
				<soap:fault use="literal" name="actualizarContadorException" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="LeadCampanias">
		<wsdl:port name="LeadCampanias" binding="tns:LeadCampanias_HttpBinding">
			<soap:address location="http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/Enlace/V1.0" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
