//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 08:57:16 AM PET 
//


package hello2.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 * <p>Java class for Lead complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Lead"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="campania"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="descripcionCampania" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="nombreCampania" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ofertasCampanha" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="nombreOferta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="descripcionOferta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="tratamientosOferta" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="nombreTratamiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="ofertaPrincipal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="canal" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="codigoTratamiento" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="fechaActivacion" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                                     &lt;attribute name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="codigoOferta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="fechaActivacion" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                           &lt;attribute name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                           &lt;attribute name="organizacion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="tipoOferta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="codigoCampania" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="prioridad" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *                 &lt;attribute name="codigoEstadoLead" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="fechaInicio" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                 &lt;attribute name="fechaFin" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                 &lt;attribute name="tipoCampania" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="producto"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="codigoLineaProducto" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="codigoProducto" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="adic" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Lead", propOrder = {
    "campania",
    "producto",
    "adic"
})
public class Lead {

    @XmlElement(required = true)
    protected Lead.Campania campania;
    @XmlElement(required = true)
    protected Lead.Producto producto;
    protected List<Lead.Adic> adic;

    /**
     * Gets the value of the campania property.
     * 
     * @return
     *     possible object is
     *     {@link Lead.Campania }
     *     
     */
    public Lead.Campania getCampania() {
        return campania;
    }

    /**
     * Sets the value of the campania property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lead.Campania }
     *     
     */
    public void setCampania(Lead.Campania value) {
        this.campania = value;
    }

    /**
     * Gets the value of the producto property.
     * 
     * @return
     *     possible object is
     *     {@link Lead.Producto }
     *     
     */
    public Lead.Producto getProducto() {
        return producto;
    }

    /**
     * Sets the value of the producto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lead.Producto }
     *     
     */
    public void setProducto(Lead.Producto value) {
        this.producto = value;
    }

    /**
     * Gets the value of the adic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lead.Adic }
     * 
     * 
     */
    public List<Lead.Adic> getAdic() {
        if (adic == null) {
            adic = new ArrayList<Lead.Adic>();
        }
        return this.adic;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Adic {

        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "value")
        protected String value;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="descripcionCampania" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="nombreCampania" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ofertasCampanha" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="nombreOferta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="descripcionOferta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="tratamientosOferta" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="nombreTratamiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="ofertaPrincipal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="canal" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="codigoTratamiento" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="fechaActivacion" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                           &lt;attribute name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="codigoOferta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="fechaActivacion" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                 &lt;attribute name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                 &lt;attribute name="organizacion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="tipoOferta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="codigoCampania" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="prioridad" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *       &lt;attribute name="codigoEstadoLead" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="fechaInicio" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *       &lt;attribute name="fechaFin" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *       &lt;attribute name="tipoCampania" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "descripcionCampania",
        "nombreCampania",
        "ofertasCampanha",
        "any"
    })
    public static class Campania {

        protected String descripcionCampania;
        protected String nombreCampania;
        @XmlElement(nillable = true)
        protected List<Lead.Campania.OfertasCampanha> ofertasCampanha;
        @XmlAnyElement(lax = true)
        protected List<Object> any;
        @XmlAttribute(name = "codigoCampania")
        protected String codigoCampania;
        @XmlAttribute(name = "prioridad")
        @XmlSchemaType(name = "unsignedInt")
        protected Long prioridad;
        @XmlAttribute(name = "codigoEstadoLead")
        protected String codigoEstadoLead;
        @XmlAttribute(name = "fechaInicio")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fechaInicio;
        @XmlAttribute(name = "fechaFin")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fechaFin;
        @XmlAttribute(name = "tipoCampania")
        protected String tipoCampania;

        /**
         * Gets the value of the descripcionCampania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescripcionCampania() {
            return descripcionCampania;
        }

        /**
         * Sets the value of the descripcionCampania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescripcionCampania(String value) {
            this.descripcionCampania = value;
        }

        /**
         * Gets the value of the nombreCampania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreCampania() {
            return nombreCampania;
        }

        /**
         * Sets the value of the nombreCampania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreCampania(String value) {
            this.nombreCampania = value;
        }

        /**
         * Gets the value of the ofertasCampanha property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ofertasCampanha property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOfertasCampanha().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Lead.Campania.OfertasCampanha }
         * 
         * 
         */
        public List<Lead.Campania.OfertasCampanha> getOfertasCampanha() {
            if (ofertasCampanha == null) {
                ofertasCampanha = new ArrayList<Lead.Campania.OfertasCampanha>();
            }
            return this.ofertasCampanha;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * {@link Element }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

        /**
         * Gets the value of the codigoCampania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoCampania() {
            return codigoCampania;
        }

        /**
         * Sets the value of the codigoCampania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoCampania(String value) {
            this.codigoCampania = value;
        }

        /**
         * Gets the value of the prioridad property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getPrioridad() {
            return prioridad;
        }

        /**
         * Sets the value of the prioridad property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setPrioridad(Long value) {
            this.prioridad = value;
        }

        /**
         * Gets the value of the codigoEstadoLead property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoEstadoLead() {
            return codigoEstadoLead;
        }

        /**
         * Sets the value of the codigoEstadoLead property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoEstadoLead(String value) {
            this.codigoEstadoLead = value;
        }

        /**
         * Gets the value of the fechaInicio property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaInicio() {
            return fechaInicio;
        }

        /**
         * Sets the value of the fechaInicio property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaInicio(XMLGregorianCalendar value) {
            this.fechaInicio = value;
        }

        /**
         * Gets the value of the fechaFin property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaFin() {
            return fechaFin;
        }

        /**
         * Sets the value of the fechaFin property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaFin(XMLGregorianCalendar value) {
            this.fechaFin = value;
        }

        /**
         * Gets the value of the tipoCampania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoCampania() {
            return tipoCampania;
        }

        /**
         * Sets the value of the tipoCampania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoCampania(String value) {
            this.tipoCampania = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="nombreOferta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="descripcionOferta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="tratamientosOferta" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="nombreTratamiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="ofertaPrincipal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="canal" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="codigoTratamiento" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="fechaActivacion" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *                 &lt;attribute name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="codigoOferta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="fechaActivacion" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *       &lt;attribute name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *       &lt;attribute name="organizacion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="tipoOferta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nombreOferta",
            "descripcionOferta",
            "tratamientosOferta"
        })
        public static class OfertasCampanha {

            protected String nombreOferta;
            protected String descripcionOferta;
            @XmlElement(nillable = true)
            protected List<Lead.Campania.OfertasCampanha.TratamientosOferta> tratamientosOferta;
            @XmlAttribute(name = "codigoOferta")
            protected String codigoOferta;
            @XmlAttribute(name = "fechaActivacion")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fechaActivacion;
            @XmlAttribute(name = "fechaVencimiento")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fechaVencimiento;
            @XmlAttribute(name = "organizacion")
            protected String organizacion;
            @XmlAttribute(name = "tipoOferta")
            protected String tipoOferta;

            /**
             * Gets the value of the nombreOferta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombreOferta() {
                return nombreOferta;
            }

            /**
             * Sets the value of the nombreOferta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombreOferta(String value) {
                this.nombreOferta = value;
            }

            /**
             * Gets the value of the descripcionOferta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescripcionOferta() {
                return descripcionOferta;
            }

            /**
             * Sets the value of the descripcionOferta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescripcionOferta(String value) {
                this.descripcionOferta = value;
            }

            /**
             * Gets the value of the tratamientosOferta property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tratamientosOferta property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTratamientosOferta().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Lead.Campania.OfertasCampanha.TratamientosOferta }
             * 
             * 
             */
            public List<Lead.Campania.OfertasCampanha.TratamientosOferta> getTratamientosOferta() {
                if (tratamientosOferta == null) {
                    tratamientosOferta = new ArrayList<Lead.Campania.OfertasCampanha.TratamientosOferta>();
                }
                return this.tratamientosOferta;
            }

            /**
             * Gets the value of the codigoOferta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigoOferta() {
                return codigoOferta;
            }

            /**
             * Sets the value of the codigoOferta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodigoOferta(String value) {
                this.codigoOferta = value;
            }

            /**
             * Gets the value of the fechaActivacion property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFechaActivacion() {
                return fechaActivacion;
            }

            /**
             * Sets the value of the fechaActivacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFechaActivacion(XMLGregorianCalendar value) {
                this.fechaActivacion = value;
            }

            /**
             * Gets the value of the fechaVencimiento property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFechaVencimiento() {
                return fechaVencimiento;
            }

            /**
             * Sets the value of the fechaVencimiento property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFechaVencimiento(XMLGregorianCalendar value) {
                this.fechaVencimiento = value;
            }

            /**
             * Gets the value of the organizacion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrganizacion() {
                return organizacion;
            }

            /**
             * Sets the value of the organizacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrganizacion(String value) {
                this.organizacion = value;
            }

            /**
             * Gets the value of the tipoOferta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoOferta() {
                return tipoOferta;
            }

            /**
             * Sets the value of the tipoOferta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoOferta(String value) {
                this.tipoOferta = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="nombreTratamiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="ofertaPrincipal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="canal" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="codigoTratamiento" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="fechaActivacion" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
             *       &lt;attribute name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nombreTratamiento",
                "ofertaPrincipal",
                "any"
            })
            public static class TratamientosOferta {

                protected String nombreTratamiento;
                protected String ofertaPrincipal;
                @XmlAnyElement(lax = true)
                protected List<Object> any;
                @XmlAttribute(name = "canal")
                protected String canal;
                @XmlAttribute(name = "codigoTratamiento")
                protected String codigoTratamiento;
                @XmlAttribute(name = "fechaActivacion")
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar fechaActivacion;
                @XmlAttribute(name = "fechaVencimiento")
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar fechaVencimiento;

                /**
                 * Gets the value of the nombreTratamiento property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNombreTratamiento() {
                    return nombreTratamiento;
                }

                /**
                 * Sets the value of the nombreTratamiento property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNombreTratamiento(String value) {
                    this.nombreTratamiento = value;
                }

                /**
                 * Gets the value of the ofertaPrincipal property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOfertaPrincipal() {
                    return ofertaPrincipal;
                }

                /**
                 * Sets the value of the ofertaPrincipal property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOfertaPrincipal(String value) {
                    this.ofertaPrincipal = value;
                }

                /**
                 * Gets the value of the any property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the any property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAny().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Object }
                 * {@link Element }
                 * 
                 * 
                 */
                public List<Object> getAny() {
                    if (any == null) {
                        any = new ArrayList<Object>();
                    }
                    return this.any;
                }

                /**
                 * Gets the value of the canal property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCanal() {
                    return canal;
                }

                /**
                 * Sets the value of the canal property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCanal(String value) {
                    this.canal = value;
                }

                /**
                 * Gets the value of the codigoTratamiento property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodigoTratamiento() {
                    return codigoTratamiento;
                }

                /**
                 * Sets the value of the codigoTratamiento property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodigoTratamiento(String value) {
                    this.codigoTratamiento = value;
                }

                /**
                 * Gets the value of the fechaActivacion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getFechaActivacion() {
                    return fechaActivacion;
                }

                /**
                 * Sets the value of the fechaActivacion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setFechaActivacion(XMLGregorianCalendar value) {
                    this.fechaActivacion = value;
                }

                /**
                 * Gets the value of the fechaVencimiento property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getFechaVencimiento() {
                    return fechaVencimiento;
                }

                /**
                 * Sets the value of the fechaVencimiento property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setFechaVencimiento(XMLGregorianCalendar value) {
                    this.fechaVencimiento = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="codigoLineaProducto" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="codigoProducto" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "any"
    })
    public static class Producto {

        @XmlElement(required = true)
        protected String description;
        @XmlAnyElement(lax = true)
        protected List<Object> any;
        @XmlAttribute(name = "codigoLineaProducto")
        protected String codigoLineaProducto;
        @XmlAttribute(name = "codigoProducto")
        protected String codigoProducto;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * {@link Element }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

        /**
         * Gets the value of the codigoLineaProducto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoLineaProducto() {
            return codigoLineaProducto;
        }

        /**
         * Sets the value of the codigoLineaProducto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoLineaProducto(String value) {
            this.codigoLineaProducto = value;
        }

        /**
         * Gets the value of the codigoProducto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoProducto() {
            return codigoProducto;
        }

        /**
         * Sets the value of the codigoProducto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoProducto(String value) {
            this.codigoProducto = value;
        }

    }

}
