//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 08:57:16 AM PET 
//


package hello2.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hello2.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultarLead_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "consultarLead");
    private final static QName _ConsultarLeadResponse_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "consultarLeadResponse");
    private final static QName _ConsultarLeadException_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "consultarLeadException");
    private final static QName _ActualizarLead_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "actualizarLead");
    private final static QName _ActualizarLeadResponse_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "actualizarLeadResponse");
    private final static QName _ActualizarLeadException_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "actualizarLeadException");
    private final static QName _ActualizarContador_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "actualizarContador");
    private final static QName _ActualizarContadorResponse_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "actualizarContadorResponse");
    private final static QName _ActualizarContadorException_QNAME = new QName("http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", "actualizarContadorException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hello2.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericException }
     * 
     */
    public GenericException createGenericException() {
        return new GenericException();
    }

    /**
     * Create an instance of {@link Lead }
     * 
     */
    public Lead createLead() {
        return new Lead();
    }

    /**
     * Create an instance of {@link Lead.Campania }
     * 
     */
    public Lead.Campania createLeadCampania() {
        return new Lead.Campania();
    }

    /**
     * Create an instance of {@link Lead.Campania.OfertasCampanha }
     * 
     */
    public Lead.Campania.OfertasCampanha createLeadCampaniaOfertasCampanha() {
        return new Lead.Campania.OfertasCampanha();
    }

    /**
     * Create an instance of {@link ActualizarContadorException }
     * 
     */
    public ActualizarContadorException createActualizarContadorException() {
        return new ActualizarContadorException();
    }

    /**
     * Create an instance of {@link ActualizarLeadException }
     * 
     */
    public ActualizarLeadException createActualizarLeadException() {
        return new ActualizarLeadException();
    }

    /**
     * Create an instance of {@link ConsultarLeadException }
     * 
     */
    public ConsultarLeadException createConsultarLeadException() {
        return new ConsultarLeadException();
    }

    /**
     * Create an instance of {@link ConsultarLeadResponse }
     * 
     */
    public ConsultarLeadResponse createConsultarLeadResponse() {
        return new ConsultarLeadResponse();
    }

    /**
     * Create an instance of {@link ConsultarLead }
     * 
     */
    public ConsultarLead createConsultarLead() {
        return new ConsultarLead();
    }

    /**
     * Create an instance of {@link ActualizarLead }
     * 
     */
    public ActualizarLead createActualizarLead() {
        return new ActualizarLead();
    }

    /**
     * Create an instance of {@link ActualizarLeadResponse }
     * 
     */
    public ActualizarLeadResponse createActualizarLeadResponse() {
        return new ActualizarLeadResponse();
    }

    /**
     * Create an instance of {@link ActualizarContador }
     * 
     */
    public ActualizarContador createActualizarContador() {
        return new ActualizarContador();
    }

    /**
     * Create an instance of {@link ActualizarContadorResponse }
     * 
     */
    public ActualizarContadorResponse createActualizarContadorResponse() {
        return new ActualizarContadorResponse();
    }

    /**
     * Create an instance of {@link GenericException.DataError }
     * 
     */
    public GenericException.DataError createGenericExceptionDataError() {
        return new GenericException.DataError();
    }

    /**
     * Create an instance of {@link Lead.Producto }
     * 
     */
    public Lead.Producto createLeadProducto() {
        return new Lead.Producto();
    }

    /**
     * Create an instance of {@link Lead.Adic }
     * 
     */
    public Lead.Adic createLeadAdic() {
        return new Lead.Adic();
    }

    /**
     * Create an instance of {@link Lead.Campania.OfertasCampanha.TratamientosOferta }
     * 
     */
    public Lead.Campania.OfertasCampanha.TratamientosOferta createLeadCampaniaOfertasCampanhaTratamientosOferta() {
        return new Lead.Campania.OfertasCampanha.TratamientosOferta();
    }

    /**
     * Create an instance of {@link ActualizarContadorException.Errors }
     * 
     */
    public ActualizarContadorException.Errors createActualizarContadorExceptionErrors() {
        return new ActualizarContadorException.Errors();
    }

    /**
     * Create an instance of {@link ActualizarLeadException.Errors }
     * 
     */
    public ActualizarLeadException.Errors createActualizarLeadExceptionErrors() {
        return new ActualizarLeadException.Errors();
    }

    /**
     * Create an instance of {@link ConsultarLeadException.Errors }
     * 
     */
    public ConsultarLeadException.Errors createConsultarLeadExceptionErrors() {
        return new ConsultarLeadException.Errors();
    }

    /**
     * Create an instance of {@link ConsultarLeadResponse.Cliente }
     * 
     */
    public ConsultarLeadResponse.Cliente createConsultarLeadResponseCliente() {
        return new ConsultarLeadResponse.Cliente();
    }

    /**
     * Create an instance of {@link ConsultarLeadResponse.Leads }
     * 
     */
    public ConsultarLeadResponse.Leads createConsultarLeadResponseLeads() {
        return new ConsultarLeadResponse.Leads();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarLead }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "consultarLead")
    public JAXBElement<ConsultarLead> createConsultarLead(ConsultarLead value) {
        return new JAXBElement<ConsultarLead>(_ConsultarLead_QNAME, ConsultarLead.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarLeadResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "consultarLeadResponse")
    public JAXBElement<ConsultarLeadResponse> createConsultarLeadResponse(ConsultarLeadResponse value) {
        return new JAXBElement<ConsultarLeadResponse>(_ConsultarLeadResponse_QNAME, ConsultarLeadResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarLeadException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "consultarLeadException")
    public JAXBElement<ConsultarLeadException> createConsultarLeadException(ConsultarLeadException value) {
        return new JAXBElement<ConsultarLeadException>(_ConsultarLeadException_QNAME, ConsultarLeadException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizarLead }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "actualizarLead")
    public JAXBElement<ActualizarLead> createActualizarLead(ActualizarLead value) {
        return new JAXBElement<ActualizarLead>(_ActualizarLead_QNAME, ActualizarLead.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizarLeadResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "actualizarLeadResponse")
    public JAXBElement<ActualizarLeadResponse> createActualizarLeadResponse(ActualizarLeadResponse value) {
        return new JAXBElement<ActualizarLeadResponse>(_ActualizarLeadResponse_QNAME, ActualizarLeadResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizarLeadException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "actualizarLeadException")
    public JAXBElement<ActualizarLeadException> createActualizarLeadException(ActualizarLeadException value) {
        return new JAXBElement<ActualizarLeadException>(_ActualizarLeadException_QNAME, ActualizarLeadException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizarContador }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "actualizarContador")
    public JAXBElement<ActualizarContador> createActualizarContador(ActualizarContador value) {
        return new JAXBElement<ActualizarContador>(_ActualizarContador_QNAME, ActualizarContador.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizarContadorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "actualizarContadorResponse")
    public JAXBElement<ActualizarContadorResponse> createActualizarContadorResponse(ActualizarContadorResponse value) {
        return new JAXBElement<ActualizarContadorResponse>(_ActualizarContadorResponse_QNAME, ActualizarContadorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizarContadorException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ibk.com/intf/InformacionEventos/ContactosVisitas/LeadCampanias/V1.0", name = "actualizarContadorException")
    public JAXBElement<ActualizarContadorException> createActualizarContadorException(ActualizarContadorException value) {
        return new JAXBElement<ActualizarContadorException>(_ActualizarContadorException_QNAME, ActualizarContadorException.class, null, value);
    }

}
